
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karmada-dashboard-prod
resources:
  - ../../base
patches:
  - path: values.yaml
    target:
      kind: ConfigMap
      name: karmada-dashboard
