apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.18.0.5:5443
  name: karmada-dashboard
contexts:
- context:
    cluster: karmada-dashboard
    user: karmada-dashboard
  name: karmada-dashboard
current-context: karmada-dashboard
kind: Config
users:
- name: karmada-dashboard
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InVVVFRhSzhOSWF5OWlMVlc0M0xNak02RXJTSl92cU5ON1V2WmtTekttZkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrYXJtYWRhLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrYXJtYWRhLWRhc2hib2FyZC1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoia2FybWFkYS1kYXNoYm9hcmQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJiNmI3MDRjNi0xMmEyLTRkNzktYTkxMS03MGM5NjZjYWE4NTAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a2FybWFkYS1zeXN0ZW06a2FybWFkYS1kYXNoYm9hcmQifQ.qvdtMxr3brJWVrPl3XYEpMpdvVhto4EBh3As1vVPfr2QW2Z0AYQG0gmqflmD3uUwQetajq6TbO1rUQ_A1vb_dUHIhnaLujII3jcBiZknYtk34CVCVGh3j9iIGiOyRQJ6a4qM5UeXIQGlGGbATXp6fvEJQopulN9JEfEQZp9DDa_9EIqB3M7DRD-KQHYzLuWWVofReu59yJYAXtJXvksktR5gvuny-pBng5l2v5c5HuBqiqNOErc-dmp9qjCc7JV1NWHEKVhMMovymGvqcnR5lpzF1h35IvVG_C0v_xQbBoEkggtTOSSLblklDxQ5wfbgloe6PTAYueIDSZtYh8d2xOlmZnb11tqkUtjTVSVTgLpczhwQbUTt_aQXycs6w_UMyqIETsHK78BmcBJoUB2fBrRO7SobkrupJQUn12HeWMTNvH2nTxgJl-Ib7c4GtV11oSwcTR5BlQraCLuCk7debhGU7Q_FFUJsdWWXRYU14ldzqh2Hs0enzxTt8YN25wtk