apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-karmada-dashboard
  namespace: karmada-system
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karmada-dashboard-web
                port:
                  number: 8000


