
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karmada-dashboard-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karmada-io/dashboard.git
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: karmada-dashboard-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
