name: Push released terminal image to DockerHub

on:
  workflow_dispatch:
    inputs:
      KARMADACTL_VERSION:
        description: 'karmadactl version'
        required: true
        type: string
      KUBECTL_VERSION:
        description: 'kubectl version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-and-push-terminal:
    name: build and push web image
    # if: ${{ github.repository == 'karmada-io/dashboard' }}
    runs-on: ubuntu-22.04
    env:
      #IMAGE_NAME: karmada/karmada-dashboard-ttyd
      IMAGE_NAME: warjiang/karmada-dashboard-terminal
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: detect misc info
        id: misc
        run: |
          echo "os=$(go env GOHOSTOS)" >> $GITHUB_OUTPUT
          echo "arch=$(go env GOHOSTARCH)" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT
          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "karmadactl_version=${{ github.event.inputs.KARMADACTL_VERSION }}" >> $GITHUB_OUTPUT
          echo "kubectl_version=${{ github.event.inputs.KUBECTL_VERSION }}" >> $GITHUB_OUTPUT
      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          file: "cluster/images/build-terminal.Dockerfile"
          context: "."
          push: true
          # tags: ${{ steps.misc.outputs.image_name }}:${{ github.ref_name }}
          tags: ${{ steps.misc.outputs.image_name }}:latest
          platforms: ${{ steps.misc.outputs.platforms }}
          build-args: |
            KARMADACTL_VERSION=${{ steps.misc.outputs.karmadactl_version }}
            KUBECTL_VERSION=${{ steps.misc.outputs.kubectl_version }}

